**Numpy**

axis 1 is the direction along the coloumn

axis 0 is the direction along the row

In [ ]:
import numpy as np

In [ ]:
b=np.arange(0,6)
print(b)

[0 1 2 3 4 5]


In [ ]:
b=np.arange(0,6,0.5)
print(b)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]


In [ ]:
b=np.arange(0,6).reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]


In [ ]:
e=np.arange(0,6).reshape(3,2)
print(e)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
b.ndim

#ndim means number of dimensions

2

In [ ]:
e.ndim

2

In [ ]:
np.sum(b,axis=0)


#0+3 , 1+4 5+2

array([3, 5, 7])

In [ ]:
np.sum(b,axis=1)

#Answer is sumation of rows

array([ 3, 12])

In [ ]:
import numpy as np
np_array_1s = np.array([[1,1,1],[1,1,1]])
np_array_9s = np.array([[9,9,9],[9,9,9]])

In [ ]:
type(np_array_1s)

numpy.ndarray

In [ ]:
#ndarray means.... n dimensionl array

In [ ]:
np.concatenate([np_array_1s, np_array_9s], axis = 0)

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [ ]:
np.concatenate([np_array_1s, np_array_9s], axis = 1)

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

1 Dimensional numpy  arrays have only one axis and that axis is axis-0

In [ ]:
b=np.array([11,22,33])

In [ ]:
b.ndim

1

In [ ]:
np_array_1s_1dim = np.array([1,1,1])
np_array_9s_1dim = np.array([9,9,9])

In [ ]:
np.concatenate([np_array_1s_1dim, np_array_9s_1dim], axis = 0)

array([1, 1, 1, 9, 9, 9])

In [ ]:
c=np.array([1,2,3])

In [ ]:
c.shape

(3,)

8 bits =1 Byte
32 bits = 4 byte

In [ ]:
#2-D array
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
b=np.array([[9,8,7],[6,5,4]])
print(b)
print(b.dtype)

[[9 8 7]
 [6 5 4]]
int64


In [ ]:
b.size

6

In [ ]:
b.itemsize

8

In [ ]:
b.nbytes

48

In [ ]:
a= np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
f= np.array([[1,2,3],[5,6,7], [8,9,10],[12,13,14]])
print(f)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]
 [12 13 14]]


In [ ]:
a.shape

(2, 7)

In [ ]:
f.shape

(4, 3)

In [ ]:
a[0,3]

4

In [ ]:
# Difference between range & arange

In [ ]:
d=